// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: net/bingyan/hust_uptime/v1/check_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_net_bingyan_hust_uptime_v1_check_service_proto protoreflect.FileDescriptor

const file_net_bingyan_hust_uptime_v1_check_service_proto_rawDesc = "" +
	"\n" +
	".net/bingyan/hust_uptime/v1/check_service.proto\x12\x1anet.bingyan.hust_uptime.v1\x1a%net/bingyan/hust_uptime/v1/task.proto2\xe5\x01\n" +
	"\fCheckService\x12d\n" +
	"\n" +
	"WatchTasks\x12-.net.bingyan.hust_uptime.v1.WatchTasksRequest\x1a%.net.bingyan.hust_uptime.v1.CheckTask0\x01\x12o\n" +
	"\fReportResult\x12..net.bingyan.hust_uptime.v1.CheckResultRequest\x1a/.net.bingyan.hust_uptime.v1.CheckResultResponseB3Z1github.com/BingyanStudio/is-hust-online/pkg/protob\x06proto3"

var file_net_bingyan_hust_uptime_v1_check_service_proto_goTypes = []any{
	(*WatchTasksRequest)(nil),   // 0: net.bingyan.hust_uptime.v1.WatchTasksRequest
	(*CheckResultRequest)(nil),  // 1: net.bingyan.hust_uptime.v1.CheckResultRequest
	(*CheckTask)(nil),           // 2: net.bingyan.hust_uptime.v1.CheckTask
	(*CheckResultResponse)(nil), // 3: net.bingyan.hust_uptime.v1.CheckResultResponse
}
var file_net_bingyan_hust_uptime_v1_check_service_proto_depIdxs = []int32{
	0, // 0: net.bingyan.hust_uptime.v1.CheckService.WatchTasks:input_type -> net.bingyan.hust_uptime.v1.WatchTasksRequest
	1, // 1: net.bingyan.hust_uptime.v1.CheckService.ReportResult:input_type -> net.bingyan.hust_uptime.v1.CheckResultRequest
	2, // 2: net.bingyan.hust_uptime.v1.CheckService.WatchTasks:output_type -> net.bingyan.hust_uptime.v1.CheckTask
	3, // 3: net.bingyan.hust_uptime.v1.CheckService.ReportResult:output_type -> net.bingyan.hust_uptime.v1.CheckResultResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_net_bingyan_hust_uptime_v1_check_service_proto_init() }
func file_net_bingyan_hust_uptime_v1_check_service_proto_init() {
	if File_net_bingyan_hust_uptime_v1_check_service_proto != nil {
		return
	}
	file_net_bingyan_hust_uptime_v1_task_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_net_bingyan_hust_uptime_v1_check_service_proto_rawDesc), len(file_net_bingyan_hust_uptime_v1_check_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_net_bingyan_hust_uptime_v1_check_service_proto_goTypes,
		DependencyIndexes: file_net_bingyan_hust_uptime_v1_check_service_proto_depIdxs,
	}.Build()
	File_net_bingyan_hust_uptime_v1_check_service_proto = out.File
	file_net_bingyan_hust_uptime_v1_check_service_proto_goTypes = nil
	file_net_bingyan_hust_uptime_v1_check_service_proto_depIdxs = nil
}
