// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: net/bingyan/hust_uptime/v1/check.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckType int32

const (
	CheckType_CHECK_TYPE_UNKNOWN CheckType = 0
	CheckType_CHECK_TYPE_HTTP    CheckType = 1
	CheckType_CHECK_TYPE_PING    CheckType = 2
	CheckType_CHECK_TYPE_TCP     CheckType = 4
	CheckType_CHECK_TYPE_OTHER   CheckType = 8
)

// Enum value maps for CheckType.
var (
	CheckType_name = map[int32]string{
		0: "CHECK_TYPE_UNKNOWN",
		1: "CHECK_TYPE_HTTP",
		2: "CHECK_TYPE_PING",
		4: "CHECK_TYPE_TCP",
		8: "CHECK_TYPE_OTHER",
	}
	CheckType_value = map[string]int32{
		"CHECK_TYPE_UNKNOWN": 0,
		"CHECK_TYPE_HTTP":    1,
		"CHECK_TYPE_PING":    2,
		"CHECK_TYPE_TCP":     4,
		"CHECK_TYPE_OTHER":   8,
	}
)

func (x CheckType) Enum() *CheckType {
	p := new(CheckType)
	*p = x
	return p
}

func (x CheckType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckType) Descriptor() protoreflect.EnumDescriptor {
	return file_net_bingyan_hust_uptime_v1_check_proto_enumTypes[0].Descriptor()
}

func (CheckType) Type() protoreflect.EnumType {
	return &file_net_bingyan_hust_uptime_v1_check_proto_enumTypes[0]
}

func (x CheckType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckType.Descriptor instead.
func (CheckType) EnumDescriptor() ([]byte, []int) {
	return file_net_bingyan_hust_uptime_v1_check_proto_rawDescGZIP(), []int{0}
}

type ErrorType int32

const (
	ErrorType_ERROR_TYPE_NO_ERROR         ErrorType = 0
	ErrorType_ERROR_TYPE_HTTP_UNREACHABLE ErrorType = 1
	ErrorType_ERROR_TYPE_HTTP_TIMEOUT     ErrorType = 2
	ErrorType_ERROR_TYPE_HTTP_OTHER       ErrorType = 3
	ErrorType_ERROR_TYPE_PING_TIMEOUT     ErrorType = 4
	ErrorType_ERROR_TYPE_PING_UNREACHABLE ErrorType = 5
	ErrorType_ERROR_TYPE_TCP_TIMEOUT      ErrorType = 6
	ErrorType_ERROR_TYPE_TCP_UNREACHABLE  ErrorType = 7
)

// Enum value maps for ErrorType.
var (
	ErrorType_name = map[int32]string{
		0: "ERROR_TYPE_NO_ERROR",
		1: "ERROR_TYPE_HTTP_UNREACHABLE",
		2: "ERROR_TYPE_HTTP_TIMEOUT",
		3: "ERROR_TYPE_HTTP_OTHER",
		4: "ERROR_TYPE_PING_TIMEOUT",
		5: "ERROR_TYPE_PING_UNREACHABLE",
		6: "ERROR_TYPE_TCP_TIMEOUT",
		7: "ERROR_TYPE_TCP_UNREACHABLE",
	}
	ErrorType_value = map[string]int32{
		"ERROR_TYPE_NO_ERROR":         0,
		"ERROR_TYPE_HTTP_UNREACHABLE": 1,
		"ERROR_TYPE_HTTP_TIMEOUT":     2,
		"ERROR_TYPE_HTTP_OTHER":       3,
		"ERROR_TYPE_PING_TIMEOUT":     4,
		"ERROR_TYPE_PING_UNREACHABLE": 5,
		"ERROR_TYPE_TCP_TIMEOUT":      6,
		"ERROR_TYPE_TCP_UNREACHABLE":  7,
	}
)

func (x ErrorType) Enum() *ErrorType {
	p := new(ErrorType)
	*p = x
	return p
}

func (x ErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_net_bingyan_hust_uptime_v1_check_proto_enumTypes[1].Descriptor()
}

func (ErrorType) Type() protoreflect.EnumType {
	return &file_net_bingyan_hust_uptime_v1_check_proto_enumTypes[1]
}

func (x ErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorType.Descriptor instead.
func (ErrorType) EnumDescriptor() ([]byte, []int) {
	return file_net_bingyan_hust_uptime_v1_check_proto_rawDescGZIP(), []int{1}
}

type CheckRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url            string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Method         string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	CheckType      CheckType              `protobuf:"varint,4,opt,name=check_type,json=checkType,proto3,enum=net.bingyan.hust_uptime.v1.CheckType" json:"check_type,omitempty"`
	TimeoutSeconds *int32                 `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3,oneof" json:"timeout_seconds,omitempty"`
	Extra          []byte                 `protobuf:"bytes,6,opt,name=extra,proto3,oneof" json:"extra,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_net_bingyan_hust_uptime_v1_check_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_net_bingyan_hust_uptime_v1_check_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_net_bingyan_hust_uptime_v1_check_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CheckRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CheckRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CheckRequest) GetCheckType() CheckType {
	if x != nil {
		return x.CheckType
	}
	return CheckType_CHECK_TYPE_UNKNOWN
}

func (x *CheckRequest) GetTimeoutSeconds() int32 {
	if x != nil && x.TimeoutSeconds != nil {
		return *x.TimeoutSeconds
	}
	return 0
}

func (x *CheckRequest) GetExtra() []byte {
	if x != nil {
		return x.Extra
	}
	return nil
}

type CheckResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success        bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorType      ErrorType              `protobuf:"varint,3,opt,name=error_type,json=errorType,proto3,enum=net.bingyan.hust_uptime.v1.ErrorType" json:"error_type,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ResponseTimeMs *int32                 `protobuf:"varint,5,opt,name=response_time_ms,json=responseTimeMs,proto3,oneof" json:"response_time_ms,omitempty"`
	Extra          []byte                 `protobuf:"bytes,6,opt,name=extra,proto3,oneof" json:"extra,omitempty"`
	CheckType      CheckType              `protobuf:"varint,7,opt,name=check_type,json=checkType,proto3,enum=net.bingyan.hust_uptime.v1.CheckType" json:"check_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_net_bingyan_hust_uptime_v1_check_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_net_bingyan_hust_uptime_v1_check_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_net_bingyan_hust_uptime_v1_check_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CheckResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CheckResponse) GetErrorType() ErrorType {
	if x != nil {
		return x.ErrorType
	}
	return ErrorType_ERROR_TYPE_NO_ERROR
}

func (x *CheckResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *CheckResponse) GetResponseTimeMs() int32 {
	if x != nil && x.ResponseTimeMs != nil {
		return *x.ResponseTimeMs
	}
	return 0
}

func (x *CheckResponse) GetExtra() []byte {
	if x != nil {
		return x.Extra
	}
	return nil
}

func (x *CheckResponse) GetCheckType() CheckType {
	if x != nil {
		return x.CheckType
	}
	return CheckType_CHECK_TYPE_UNKNOWN
}

type ServiceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsHealthy     bool                   `protobuf:"varint,1,opt,name=is_healthy,json=isHealthy,proto3" json:"is_healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Message       *string                `protobuf:"bytes,3,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceStatus) Reset() {
	*x = ServiceStatus{}
	mi := &file_net_bingyan_hust_uptime_v1_check_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStatus) ProtoMessage() {}

func (x *ServiceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_net_bingyan_hust_uptime_v1_check_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStatus.ProtoReflect.Descriptor instead.
func (*ServiceStatus) Descriptor() ([]byte, []int) {
	return file_net_bingyan_hust_uptime_v1_check_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceStatus) GetIsHealthy() bool {
	if x != nil {
		return x.IsHealthy
	}
	return false
}

func (x *ServiceStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServiceStatus) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

var File_net_bingyan_hust_uptime_v1_check_proto protoreflect.FileDescriptor

const file_net_bingyan_hust_uptime_v1_check_proto_rawDesc = "" +
	"\n" +
	"&net/bingyan/hust_uptime/v1/check.proto\x12\x1anet.bingyan.hust_uptime.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf5\x01\n" +
	"\fCheckRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12D\n" +
	"\n" +
	"check_type\x18\x04 \x01(\x0e2%.net.bingyan.hust_uptime.v1.CheckTypeR\tcheckType\x12,\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05H\x00R\x0etimeoutSeconds\x88\x01\x01\x12\x19\n" +
	"\x05extra\x18\x06 \x01(\fH\x01R\x05extra\x88\x01\x01B\x12\n" +
	"\x10_timeout_secondsB\b\n" +
	"\x06_extra\"\xe8\x02\n" +
	"\rCheckResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12D\n" +
	"\n" +
	"error_type\x18\x03 \x01(\x0e2%.net.bingyan.hust_uptime.v1.ErrorTypeR\terrorType\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12-\n" +
	"\x10response_time_ms\x18\x05 \x01(\x05H\x00R\x0eresponseTimeMs\x88\x01\x01\x12\x19\n" +
	"\x05extra\x18\x06 \x01(\fH\x01R\x05extra\x88\x01\x01\x12D\n" +
	"\n" +
	"check_type\x18\a \x01(\x0e2%.net.bingyan.hust_uptime.v1.CheckTypeR\tcheckTypeB\x13\n" +
	"\x11_response_time_msB\b\n" +
	"\x06_extra\"s\n" +
	"\rServiceStatus\x12\x1d\n" +
	"\n" +
	"is_healthy\x18\x01 \x01(\bR\tisHealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1d\n" +
	"\amessage\x18\x03 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message*w\n" +
	"\tCheckType\x12\x16\n" +
	"\x12CHECK_TYPE_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fCHECK_TYPE_HTTP\x10\x01\x12\x13\n" +
	"\x0fCHECK_TYPE_PING\x10\x02\x12\x12\n" +
	"\x0eCHECK_TYPE_TCP\x10\x04\x12\x14\n" +
	"\x10CHECK_TYPE_OTHER\x10\b*\xf7\x01\n" +
	"\tErrorType\x12\x17\n" +
	"\x13ERROR_TYPE_NO_ERROR\x10\x00\x12\x1f\n" +
	"\x1bERROR_TYPE_HTTP_UNREACHABLE\x10\x01\x12\x1b\n" +
	"\x17ERROR_TYPE_HTTP_TIMEOUT\x10\x02\x12\x19\n" +
	"\x15ERROR_TYPE_HTTP_OTHER\x10\x03\x12\x1b\n" +
	"\x17ERROR_TYPE_PING_TIMEOUT\x10\x04\x12\x1f\n" +
	"\x1bERROR_TYPE_PING_UNREACHABLE\x10\x05\x12\x1a\n" +
	"\x16ERROR_TYPE_TCP_TIMEOUT\x10\x06\x12\x1e\n" +
	"\x1aERROR_TYPE_TCP_UNREACHABLE\x10\aB3Z1github.com/BingyanStudio/is-hust-online/pkg/protob\x06proto3"

var (
	file_net_bingyan_hust_uptime_v1_check_proto_rawDescOnce sync.Once
	file_net_bingyan_hust_uptime_v1_check_proto_rawDescData []byte
)

func file_net_bingyan_hust_uptime_v1_check_proto_rawDescGZIP() []byte {
	file_net_bingyan_hust_uptime_v1_check_proto_rawDescOnce.Do(func() {
		file_net_bingyan_hust_uptime_v1_check_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_net_bingyan_hust_uptime_v1_check_proto_rawDesc), len(file_net_bingyan_hust_uptime_v1_check_proto_rawDesc)))
	})
	return file_net_bingyan_hust_uptime_v1_check_proto_rawDescData
}

var file_net_bingyan_hust_uptime_v1_check_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_net_bingyan_hust_uptime_v1_check_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_net_bingyan_hust_uptime_v1_check_proto_goTypes = []any{
	(CheckType)(0),                // 0: net.bingyan.hust_uptime.v1.CheckType
	(ErrorType)(0),                // 1: net.bingyan.hust_uptime.v1.ErrorType
	(*CheckRequest)(nil),          // 2: net.bingyan.hust_uptime.v1.CheckRequest
	(*CheckResponse)(nil),         // 3: net.bingyan.hust_uptime.v1.CheckResponse
	(*ServiceStatus)(nil),         // 4: net.bingyan.hust_uptime.v1.ServiceStatus
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_net_bingyan_hust_uptime_v1_check_proto_depIdxs = []int32{
	0, // 0: net.bingyan.hust_uptime.v1.CheckRequest.check_type:type_name -> net.bingyan.hust_uptime.v1.CheckType
	1, // 1: net.bingyan.hust_uptime.v1.CheckResponse.error_type:type_name -> net.bingyan.hust_uptime.v1.ErrorType
	5, // 2: net.bingyan.hust_uptime.v1.CheckResponse.timestamp:type_name -> google.protobuf.Timestamp
	0, // 3: net.bingyan.hust_uptime.v1.CheckResponse.check_type:type_name -> net.bingyan.hust_uptime.v1.CheckType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_net_bingyan_hust_uptime_v1_check_proto_init() }
func file_net_bingyan_hust_uptime_v1_check_proto_init() {
	if File_net_bingyan_hust_uptime_v1_check_proto != nil {
		return
	}
	file_net_bingyan_hust_uptime_v1_check_proto_msgTypes[0].OneofWrappers = []any{}
	file_net_bingyan_hust_uptime_v1_check_proto_msgTypes[1].OneofWrappers = []any{}
	file_net_bingyan_hust_uptime_v1_check_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_net_bingyan_hust_uptime_v1_check_proto_rawDesc), len(file_net_bingyan_hust_uptime_v1_check_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_net_bingyan_hust_uptime_v1_check_proto_goTypes,
		DependencyIndexes: file_net_bingyan_hust_uptime_v1_check_proto_depIdxs,
		EnumInfos:         file_net_bingyan_hust_uptime_v1_check_proto_enumTypes,
		MessageInfos:      file_net_bingyan_hust_uptime_v1_check_proto_msgTypes,
	}.Build()
	File_net_bingyan_hust_uptime_v1_check_proto = out.File
	file_net_bingyan_hust_uptime_v1_check_proto_goTypes = nil
	file_net_bingyan_hust_uptime_v1_check_proto_depIdxs = nil
}
