// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: net/bingyan/hust_uptime/v1/client.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientStatus int32

const (
	ClientStatus_CLIENT_STATUS_UNKNOWN  ClientStatus = 0
	ClientStatus_CLIENT_STATUS_ONLINE   ClientStatus = 1
	ClientStatus_CLIENT_STATUS_BUSY     ClientStatus = 2
	ClientStatus_CLIENT_STATUS_DEGRADED ClientStatus = 3
	ClientStatus_CLIENT_STATUS_OFFLINE  ClientStatus = 4
)

// Enum value maps for ClientStatus.
var (
	ClientStatus_name = map[int32]string{
		0: "CLIENT_STATUS_UNKNOWN",
		1: "CLIENT_STATUS_ONLINE",
		2: "CLIENT_STATUS_BUSY",
		3: "CLIENT_STATUS_DEGRADED",
		4: "CLIENT_STATUS_OFFLINE",
	}
	ClientStatus_value = map[string]int32{
		"CLIENT_STATUS_UNKNOWN":  0,
		"CLIENT_STATUS_ONLINE":   1,
		"CLIENT_STATUS_BUSY":     2,
		"CLIENT_STATUS_DEGRADED": 3,
		"CLIENT_STATUS_OFFLINE":  4,
	}
)

func (x ClientStatus) Enum() *ClientStatus {
	p := new(ClientStatus)
	*p = x
	return p
}

func (x ClientStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_net_bingyan_hust_uptime_v1_client_proto_enumTypes[0].Descriptor()
}

func (ClientStatus) Type() protoreflect.EnumType {
	return &file_net_bingyan_hust_uptime_v1_client_proto_enumTypes[0]
}

func (x ClientStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientStatus.Descriptor instead.
func (ClientStatus) EnumDescriptor() ([]byte, []int) {
	return file_net_bingyan_hust_uptime_v1_client_proto_rawDescGZIP(), []int{0}
}

type ClientInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Capabilities  []CheckType            `protobuf:"varint,2,rep,packed,name=capabilities,proto3,enum=net.bingyan.hust_uptime.v1.CheckType" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientInfo) Reset() {
	*x = ClientInfo{}
	mi := &file_net_bingyan_hust_uptime_v1_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfo) ProtoMessage() {}

func (x *ClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_net_bingyan_hust_uptime_v1_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfo.ProtoReflect.Descriptor instead.
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return file_net_bingyan_hust_uptime_v1_client_proto_rawDescGZIP(), []int{0}
}

func (x *ClientInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ClientInfo) GetCapabilities() []CheckType {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientInfo    *ClientInfo            `protobuf:"bytes,1,opt,name=client_info,json=clientInfo,proto3" json:"client_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_net_bingyan_hust_uptime_v1_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_net_bingyan_hust_uptime_v1_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_net_bingyan_hust_uptime_v1_client_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetClientInfo() *ClientInfo {
	if x != nil {
		return x.ClientInfo
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_net_bingyan_hust_uptime_v1_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_net_bingyan_hust_uptime_v1_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_net_bingyan_hust_uptime_v1_client_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Status        ClientStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=net.bingyan.hust_uptime.v1.ClientStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_net_bingyan_hust_uptime_v1_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_net_bingyan_hust_uptime_v1_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_net_bingyan_hust_uptime_v1_client_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() ClientStatus {
	if x != nil {
		return x.Status
	}
	return ClientStatus_CLIENT_STATUS_UNKNOWN
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ServerTime    int64                  `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_net_bingyan_hust_uptime_v1_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_net_bingyan_hust_uptime_v1_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_net_bingyan_hust_uptime_v1_client_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

type DeregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterRequest) Reset() {
	*x = DeregisterRequest{}
	mi := &file_net_bingyan_hust_uptime_v1_client_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRequest) ProtoMessage() {}

func (x *DeregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_net_bingyan_hust_uptime_v1_client_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterRequest.ProtoReflect.Descriptor instead.
func (*DeregisterRequest) Descriptor() ([]byte, []int) {
	return file_net_bingyan_hust_uptime_v1_client_proto_rawDescGZIP(), []int{5}
}

func (x *DeregisterRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type DeregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterResponse) Reset() {
	*x = DeregisterResponse{}
	mi := &file_net_bingyan_hust_uptime_v1_client_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterResponse) ProtoMessage() {}

func (x *DeregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_net_bingyan_hust_uptime_v1_client_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterResponse.ProtoReflect.Descriptor instead.
func (*DeregisterResponse) Descriptor() ([]byte, []int) {
	return file_net_bingyan_hust_uptime_v1_client_proto_rawDescGZIP(), []int{6}
}

func (x *DeregisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_net_bingyan_hust_uptime_v1_client_proto protoreflect.FileDescriptor

const file_net_bingyan_hust_uptime_v1_client_proto_rawDesc = "" +
	"\n" +
	"'net/bingyan/hust_uptime/v1/client.proto\x12\x1anet.bingyan.hust_uptime.v1\x1a&net/bingyan/hust_uptime/v1/check.proto\"g\n" +
	"\n" +
	"ClientInfo\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12I\n" +
	"\fcapabilities\x18\x02 \x03(\x0e2%.net.bingyan.hust_uptime.v1.CheckTypeR\fcapabilities\"Z\n" +
	"\x0fRegisterRequest\x12G\n" +
	"\vclient_info\x18\x01 \x01(\v2&.net.bingyan.hust_uptime.v1.ClientInfoR\n" +
	"clientInfo\"c\n" +
	"\x10RegisterResponse\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"q\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12@\n" +
	"\x06status\x18\x02 \x01(\x0e2(.net.bingyan.hust_uptime.v1.ClientStatusR\x06status\"N\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime\"0\n" +
	"\x11DeregisterRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\".\n" +
	"\x12DeregisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*\x92\x01\n" +
	"\fClientStatus\x12\x19\n" +
	"\x15CLIENT_STATUS_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14CLIENT_STATUS_ONLINE\x10\x01\x12\x16\n" +
	"\x12CLIENT_STATUS_BUSY\x10\x02\x12\x1a\n" +
	"\x16CLIENT_STATUS_DEGRADED\x10\x03\x12\x19\n" +
	"\x15CLIENT_STATUS_OFFLINE\x10\x04B3Z1github.com/BingyanStudio/is-hust-online/pkg/protob\x06proto3"

var (
	file_net_bingyan_hust_uptime_v1_client_proto_rawDescOnce sync.Once
	file_net_bingyan_hust_uptime_v1_client_proto_rawDescData []byte
)

func file_net_bingyan_hust_uptime_v1_client_proto_rawDescGZIP() []byte {
	file_net_bingyan_hust_uptime_v1_client_proto_rawDescOnce.Do(func() {
		file_net_bingyan_hust_uptime_v1_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_net_bingyan_hust_uptime_v1_client_proto_rawDesc), len(file_net_bingyan_hust_uptime_v1_client_proto_rawDesc)))
	})
	return file_net_bingyan_hust_uptime_v1_client_proto_rawDescData
}

var file_net_bingyan_hust_uptime_v1_client_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_net_bingyan_hust_uptime_v1_client_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_net_bingyan_hust_uptime_v1_client_proto_goTypes = []any{
	(ClientStatus)(0),          // 0: net.bingyan.hust_uptime.v1.ClientStatus
	(*ClientInfo)(nil),         // 1: net.bingyan.hust_uptime.v1.ClientInfo
	(*RegisterRequest)(nil),    // 2: net.bingyan.hust_uptime.v1.RegisterRequest
	(*RegisterResponse)(nil),   // 3: net.bingyan.hust_uptime.v1.RegisterResponse
	(*HeartbeatRequest)(nil),   // 4: net.bingyan.hust_uptime.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),  // 5: net.bingyan.hust_uptime.v1.HeartbeatResponse
	(*DeregisterRequest)(nil),  // 6: net.bingyan.hust_uptime.v1.DeregisterRequest
	(*DeregisterResponse)(nil), // 7: net.bingyan.hust_uptime.v1.DeregisterResponse
	(CheckType)(0),             // 8: net.bingyan.hust_uptime.v1.CheckType
}
var file_net_bingyan_hust_uptime_v1_client_proto_depIdxs = []int32{
	8, // 0: net.bingyan.hust_uptime.v1.ClientInfo.capabilities:type_name -> net.bingyan.hust_uptime.v1.CheckType
	1, // 1: net.bingyan.hust_uptime.v1.RegisterRequest.client_info:type_name -> net.bingyan.hust_uptime.v1.ClientInfo
	0, // 2: net.bingyan.hust_uptime.v1.HeartbeatRequest.status:type_name -> net.bingyan.hust_uptime.v1.ClientStatus
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_net_bingyan_hust_uptime_v1_client_proto_init() }
func file_net_bingyan_hust_uptime_v1_client_proto_init() {
	if File_net_bingyan_hust_uptime_v1_client_proto != nil {
		return
	}
	file_net_bingyan_hust_uptime_v1_check_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_net_bingyan_hust_uptime_v1_client_proto_rawDesc), len(file_net_bingyan_hust_uptime_v1_client_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_net_bingyan_hust_uptime_v1_client_proto_goTypes,
		DependencyIndexes: file_net_bingyan_hust_uptime_v1_client_proto_depIdxs,
		EnumInfos:         file_net_bingyan_hust_uptime_v1_client_proto_enumTypes,
		MessageInfos:      file_net_bingyan_hust_uptime_v1_client_proto_msgTypes,
	}.Build()
	File_net_bingyan_hust_uptime_v1_client_proto = out.File
	file_net_bingyan_hust_uptime_v1_client_proto_goTypes = nil
	file_net_bingyan_hust_uptime_v1_client_proto_depIdxs = nil
}
