// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: net/bingyan/hust_uptime/v1/client_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_net_bingyan_hust_uptime_v1_client_service_proto protoreflect.FileDescriptor

const file_net_bingyan_hust_uptime_v1_client_service_proto_rawDesc = "" +
	"\n" +
	"/net/bingyan/hust_uptime/v1/client_service.proto\x12\x1anet.bingyan.hust_uptime.v1\x1a'net/bingyan/hust_uptime/v1/client.proto2\xcd\x02\n" +
	"\rClientManager\x12e\n" +
	"\bRegister\x12+.net.bingyan.hust_uptime.v1.RegisterRequest\x1a,.net.bingyan.hust_uptime.v1.RegisterResponse\x12h\n" +
	"\tHeartbeat\x12,.net.bingyan.hust_uptime.v1.HeartbeatRequest\x1a-.net.bingyan.hust_uptime.v1.HeartbeatResponse\x12k\n" +
	"\n" +
	"Deregister\x12-.net.bingyan.hust_uptime.v1.DeregisterRequest\x1a..net.bingyan.hust_uptime.v1.DeregisterResponseB3Z1github.com/BingyanStudio/is-hust-online/pkg/protob\x06proto3"

var file_net_bingyan_hust_uptime_v1_client_service_proto_goTypes = []any{
	(*RegisterRequest)(nil),    // 0: net.bingyan.hust_uptime.v1.RegisterRequest
	(*HeartbeatRequest)(nil),   // 1: net.bingyan.hust_uptime.v1.HeartbeatRequest
	(*DeregisterRequest)(nil),  // 2: net.bingyan.hust_uptime.v1.DeregisterRequest
	(*RegisterResponse)(nil),   // 3: net.bingyan.hust_uptime.v1.RegisterResponse
	(*HeartbeatResponse)(nil),  // 4: net.bingyan.hust_uptime.v1.HeartbeatResponse
	(*DeregisterResponse)(nil), // 5: net.bingyan.hust_uptime.v1.DeregisterResponse
}
var file_net_bingyan_hust_uptime_v1_client_service_proto_depIdxs = []int32{
	0, // 0: net.bingyan.hust_uptime.v1.ClientManager.Register:input_type -> net.bingyan.hust_uptime.v1.RegisterRequest
	1, // 1: net.bingyan.hust_uptime.v1.ClientManager.Heartbeat:input_type -> net.bingyan.hust_uptime.v1.HeartbeatRequest
	2, // 2: net.bingyan.hust_uptime.v1.ClientManager.Deregister:input_type -> net.bingyan.hust_uptime.v1.DeregisterRequest
	3, // 3: net.bingyan.hust_uptime.v1.ClientManager.Register:output_type -> net.bingyan.hust_uptime.v1.RegisterResponse
	4, // 4: net.bingyan.hust_uptime.v1.ClientManager.Heartbeat:output_type -> net.bingyan.hust_uptime.v1.HeartbeatResponse
	5, // 5: net.bingyan.hust_uptime.v1.ClientManager.Deregister:output_type -> net.bingyan.hust_uptime.v1.DeregisterResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_net_bingyan_hust_uptime_v1_client_service_proto_init() }
func file_net_bingyan_hust_uptime_v1_client_service_proto_init() {
	if File_net_bingyan_hust_uptime_v1_client_service_proto != nil {
		return
	}
	file_net_bingyan_hust_uptime_v1_client_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_net_bingyan_hust_uptime_v1_client_service_proto_rawDesc), len(file_net_bingyan_hust_uptime_v1_client_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_net_bingyan_hust_uptime_v1_client_service_proto_goTypes,
		DependencyIndexes: file_net_bingyan_hust_uptime_v1_client_service_proto_depIdxs,
	}.Build()
	File_net_bingyan_hust_uptime_v1_client_service_proto = out.File
	file_net_bingyan_hust_uptime_v1_client_service_proto_goTypes = nil
	file_net_bingyan_hust_uptime_v1_client_service_proto_depIdxs = nil
}
