// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: net/bingyan/hust_uptime/v1/task.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchTasksRequest) Reset() {
	*x = WatchTasksRequest{}
	mi := &file_net_bingyan_hust_uptime_v1_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchTasksRequest) ProtoMessage() {}

func (x *WatchTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_net_bingyan_hust_uptime_v1_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchTasksRequest.ProtoReflect.Descriptor instead.
func (*WatchTasksRequest) Descriptor() ([]byte, []int) {
	return file_net_bingyan_hust_uptime_v1_task_proto_rawDescGZIP(), []int{0}
}

func (x *WatchTasksRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type CheckTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Check         *CheckRequest          `protobuf:"bytes,2,opt,name=check,proto3" json:"check,omitempty"`
	AssignedAt    int64                  `protobuf:"varint,3,opt,name=assigned_at,json=assignedAt,proto3" json:"assigned_at,omitempty"`
	Deadline      *int64                 `protobuf:"varint,4,opt,name=deadline,proto3,oneof" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTask) Reset() {
	*x = CheckTask{}
	mi := &file_net_bingyan_hust_uptime_v1_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTask) ProtoMessage() {}

func (x *CheckTask) ProtoReflect() protoreflect.Message {
	mi := &file_net_bingyan_hust_uptime_v1_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTask.ProtoReflect.Descriptor instead.
func (*CheckTask) Descriptor() ([]byte, []int) {
	return file_net_bingyan_hust_uptime_v1_task_proto_rawDescGZIP(), []int{1}
}

func (x *CheckTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CheckTask) GetCheck() *CheckRequest {
	if x != nil {
		return x.Check
	}
	return nil
}

func (x *CheckTask) GetAssignedAt() int64 {
	if x != nil {
		return x.AssignedAt
	}
	return 0
}

func (x *CheckTask) GetDeadline() int64 {
	if x != nil && x.Deadline != nil {
		return *x.Deadline
	}
	return 0
}

type CheckResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Result        *CheckResponse         `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResultRequest) Reset() {
	*x = CheckResultRequest{}
	mi := &file_net_bingyan_hust_uptime_v1_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResultRequest) ProtoMessage() {}

func (x *CheckResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_net_bingyan_hust_uptime_v1_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResultRequest.ProtoReflect.Descriptor instead.
func (*CheckResultRequest) Descriptor() ([]byte, []int) {
	return file_net_bingyan_hust_uptime_v1_task_proto_rawDescGZIP(), []int{2}
}

func (x *CheckResultRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CheckResultRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CheckResultRequest) GetResult() *CheckResponse {
	if x != nil {
		return x.Result
	}
	return nil
}

type CheckResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResultResponse) Reset() {
	*x = CheckResultResponse{}
	mi := &file_net_bingyan_hust_uptime_v1_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResultResponse) ProtoMessage() {}

func (x *CheckResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_net_bingyan_hust_uptime_v1_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResultResponse.ProtoReflect.Descriptor instead.
func (*CheckResultResponse) Descriptor() ([]byte, []int) {
	return file_net_bingyan_hust_uptime_v1_task_proto_rawDescGZIP(), []int{3}
}

func (x *CheckResultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_net_bingyan_hust_uptime_v1_task_proto protoreflect.FileDescriptor

const file_net_bingyan_hust_uptime_v1_task_proto_rawDesc = "" +
	"\n" +
	"%net/bingyan/hust_uptime/v1/task.proto\x12\x1anet.bingyan.hust_uptime.v1\x1a&net/bingyan/hust_uptime/v1/check.proto\"0\n" +
	"\x11WatchTasksRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"\xb3\x01\n" +
	"\tCheckTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12>\n" +
	"\x05check\x18\x02 \x01(\v2(.net.bingyan.hust_uptime.v1.CheckRequestR\x05check\x12\x1f\n" +
	"\vassigned_at\x18\x03 \x01(\x03R\n" +
	"assignedAt\x12\x1f\n" +
	"\bdeadline\x18\x04 \x01(\x03H\x00R\bdeadline\x88\x01\x01B\v\n" +
	"\t_deadline\"\x8d\x01\n" +
	"\x12CheckResultRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12A\n" +
	"\x06result\x18\x03 \x01(\v2).net.bingyan.hust_uptime.v1.CheckResponseR\x06result\"/\n" +
	"\x13CheckResultResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccessB3Z1github.com/BingyanStudio/is-hust-online/pkg/protob\x06proto3"

var (
	file_net_bingyan_hust_uptime_v1_task_proto_rawDescOnce sync.Once
	file_net_bingyan_hust_uptime_v1_task_proto_rawDescData []byte
)

func file_net_bingyan_hust_uptime_v1_task_proto_rawDescGZIP() []byte {
	file_net_bingyan_hust_uptime_v1_task_proto_rawDescOnce.Do(func() {
		file_net_bingyan_hust_uptime_v1_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_net_bingyan_hust_uptime_v1_task_proto_rawDesc), len(file_net_bingyan_hust_uptime_v1_task_proto_rawDesc)))
	})
	return file_net_bingyan_hust_uptime_v1_task_proto_rawDescData
}

var file_net_bingyan_hust_uptime_v1_task_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_net_bingyan_hust_uptime_v1_task_proto_goTypes = []any{
	(*WatchTasksRequest)(nil),   // 0: net.bingyan.hust_uptime.v1.WatchTasksRequest
	(*CheckTask)(nil),           // 1: net.bingyan.hust_uptime.v1.CheckTask
	(*CheckResultRequest)(nil),  // 2: net.bingyan.hust_uptime.v1.CheckResultRequest
	(*CheckResultResponse)(nil), // 3: net.bingyan.hust_uptime.v1.CheckResultResponse
	(*CheckRequest)(nil),        // 4: net.bingyan.hust_uptime.v1.CheckRequest
	(*CheckResponse)(nil),       // 5: net.bingyan.hust_uptime.v1.CheckResponse
}
var file_net_bingyan_hust_uptime_v1_task_proto_depIdxs = []int32{
	4, // 0: net.bingyan.hust_uptime.v1.CheckTask.check:type_name -> net.bingyan.hust_uptime.v1.CheckRequest
	5, // 1: net.bingyan.hust_uptime.v1.CheckResultRequest.result:type_name -> net.bingyan.hust_uptime.v1.CheckResponse
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_net_bingyan_hust_uptime_v1_task_proto_init() }
func file_net_bingyan_hust_uptime_v1_task_proto_init() {
	if File_net_bingyan_hust_uptime_v1_task_proto != nil {
		return
	}
	file_net_bingyan_hust_uptime_v1_check_proto_init()
	file_net_bingyan_hust_uptime_v1_task_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_net_bingyan_hust_uptime_v1_task_proto_rawDesc), len(file_net_bingyan_hust_uptime_v1_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_net_bingyan_hust_uptime_v1_task_proto_goTypes,
		DependencyIndexes: file_net_bingyan_hust_uptime_v1_task_proto_depIdxs,
		MessageInfos:      file_net_bingyan_hust_uptime_v1_task_proto_msgTypes,
	}.Build()
	File_net_bingyan_hust_uptime_v1_task_proto = out.File
	file_net_bingyan_hust_uptime_v1_task_proto_goTypes = nil
	file_net_bingyan_hust_uptime_v1_task_proto_depIdxs = nil
}
